package net.demilich.metastone.game.cards;

public enum CardSet {
	ANY,
	BASIC,
	CLASSIC,
	HALL_OF_FAME,
	NAXXRAMAS,
	GOBLINS_VS_GNOMES,
	BLACKROCK_MOUNTAIN,
	THE_GRAND_TOURNAMENT,
	LEAGUE_OF_EXPLORERS,
	THE_OLD_GODS,
	ONE_NIGHT_IN_KARAZHAN,
	MEAN_STREETS_OF_GADGETZAN,
	JOURNEY_TO_UNGORO,
	FROZEN_THRONE,
	KOBOLDS_AND_CATACOMBS,
	
	CUSTOM,
	SANDS_OF_TIME,
	BATTLE_FOR_ASHENVALE,
}
